# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build and auto release

on:
  # 手动触发事件
  workflow_dispatch:
#    inputs:
#      logLevel:
#        description: 'Log level'
#        required: true
#        default: 'warning'
#      tags:
#        description: 'Test some tags'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout lib repo
      uses: actions/checkout@v3
      with:
        repository: hezhenpan/aws-private-lib
        path: aws-private-lib
        token: ${{ secrets.GH_TK }}

    - name: Checkout main repo
      uses: actions/checkout@v3
      with:
        path: maincode

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: "1.20"

    - name: Build Go Binary File
      run: go mod tidy && CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o goapp -v ./...
      working-directory: ./maincode

    - name: Release Go Binary File For Download
      uses: actions/upload-artifact@v3
      with:
        name: goapp-bin
        path: ./maincode/goapp

    - name: Build the Docker image
      run: |
        docker build . --file ./maincode/ln.dockerfile --tag goapp:$(date +%s)
        echo "image=goapp:$(date +%s)" >> $GITHUB_OUTPUT

